project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - coursework.qmd
    - cv.qmd

website:
  title: "Etienne Compérat"
  favicon: img\logo_round.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: coursework.qmd
        text: Coursework
      - cv.qmd

format:
  html:
    theme: jollia
    css: styles.css
    toc: true
