project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - coursework.qmd
    - courses.qmd
    - cv.qmd

website:
  title: "Etienne Compérat"
  description: "Pre-doctoral Fellow in Economics at University of Zurich. Economic History, Political Economy, and Urban Economics."
  site-url: "https://ecomperat.github.io"
  favicon: img\logo_round.png
  open-graph: true
  twitter-card: true
  image: "img/snapshot2.jpg"
  google-analytics: "G-XXXXXXXXXX"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Coursework
        menu:
          - href: coursework.qmd
            text: Past Assignments
          - href: courses.qmd
            text: Courses
      - cv.qmd

format:
  html:
    theme: jollia
    css: styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    include-after-body: analytics.js
