project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - coursework.qmd
    - courses.qmd
    - cv.qmd

website:
  title: "Etienne Compérat"
  favicon: img\logo_round.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Coursework
        menu:
          - href: coursework.qmd
            text: Past Assignments
          - href: courses.qmd
            text: Courses
      - cv.qmd

format:
  html:
    theme: jollia
    css: styles.css
    toc: true
